// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj0gIIKDv5bonfAgLnZxJ-ZRFX3B-Rvic',
    appId: '1:592102292296:web:769b0fa6aa200eefb2d17d',
    messagingSenderId: '592102292296',
    projectId: 'flutter-chat-app-4215c',
    authDomain: 'flutter-chat-app-4215c.firebaseapp.com',
    storageBucket: 'flutter-chat-app-4215c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPFT8P5YDRiv84lpDfzRINDUoEtcrcrgY',
    appId: '1:592102292296:android:0ef5d2566e06d3c1b2d17d',
    messagingSenderId: '592102292296',
    projectId: 'flutter-chat-app-4215c',
    storageBucket: 'flutter-chat-app-4215c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXnLj1iA7OcKDrJosC_uT_DGP7nhhNrms',
    appId: '1:592102292296:ios:53da8c47352d0a27b2d17d',
    messagingSenderId: '592102292296',
    projectId: 'flutter-chat-app-4215c',
    storageBucket: 'flutter-chat-app-4215c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

}